const router = require('express').Router()
const olahdata = require('../controllers/olahdataController')
const {
    isAuth
} = require("../midleware/auth");

router.get('/allproduk', isAuth, olahdata.allProduk)
router.post('/pulsaperreseller', isAuth, olahdata.pulsaPerReseller)
router.get('/getProduk', isAuth, olahdata.getProduk)
router.get('/banner', olahdata.banner)
router.get('/info', olahdata.info)
router.get('/allbank', olahdata.getBank)
router.get('/promo', olahdata.promo)
// router.post('/promooperator', isAuth, olahdata.promoOperator)
// router.post('/paketdatainjek', isAuth, olahdata.paketDataInjekPerReseller)
// router.post('/getproduk', isAuth, olahdata.getProduk)
// router.post('/pakettelpdansms', isAuth, olahdata.paketTelp)
// router.post('/tokenpln', isAuth, olahdata.tokenPln)
// router.post('/roaming', isAuth, olahdata.roaming)
// router.post('/internasional', isAuth, olahdata.listpulsainternasional)
// router.post('/internasional/:id', isAuth, olahdata.getpulsainternasional)
// router.post('/finance', isAuth, olahdata.finance)
// router.post('/pascabayar', isAuth, olahdata.pascaBayar)
// router.post('/pam', isAuth, olahdata.pam)
// router.post('/voucherwifiid', isAuth, olahdata.voucherWifiId)
// router.post('/saldoovo', isAuth, olahdata.saldoOvo)
// router.post('/saldodana', isAuth, olahdata.saldoDana)
// router.post('/gojekcustomer', isAuth, olahdata.gojekCustomer)
// router.post('/gojekdriver', isAuth, olahdata.gojekDriver)
// router.post('/grabcustomer', isAuth, olahdata.grabCustomer)
// router.post('/grabdriver', isAuth, olahdata.grabDriver)
// router.post('/game', isAuth, olahdata.game)
// router.post('/produkgame', isAuth, olahdata.produkGame)
// router.post('/saldoshopee', isAuth, olahdata.saldoShopee)
// router.post('/emoney', isAuth, olahdata.emoney)
// router.post('/produklinkaja', isAuth, olahdata.produkLinkaja)
// router.post('/inettv', isAuth, olahdata.inetTv)
// router.post('/produkpbb', isAuth, olahdata.produkPbb)
// router.post('/produkent', isAuth, olahdata.produkEnt)
// router.post('/getkodeoperator', isAuth, olahdata.getKodeOperator)

module.exports = router